"""Optional adapters for existing speech-inference APIs."""

from .legacy_whisper import (
    LEGACY_WHISPER_ENVELOPE_VERSION,
    LegacyAdapterError,
    LegacyExecutionMeasurements,
    LegacyExecutionProfile,
    LegacyInputProvenance,
    LegacyOptionsMutationError,
    LegacyPayloadError,
    LegacyTranscribeOptions,
    LegacyTranscriptionEnvelope,
    LegacyTranscriptionRetainedError,
    LegacyWhisperAdapter,
    LegacyWhisperModel,
    ModelIdentityProbe,
)
from .native_stream import (
    BOUNDED_PREFIX_PROFILE,
    AudioBufferFullError,
    AudioSequenceError,
    NativeStreamConfig,
    NativeStreamError,
    NativeTranscriptStream,
    StreamEventKind,
    StreamMetrics,
    TranscriptEvent,
)
from .native_whisper import (
    NativeAdapterError,
    NativeDecodeContractError,
    NativeDecodeOptions,
    NativeDecodeRun,
    NativeDependencyError,
    NativeExecutionProfile,
    NativeModelIdentityProbe,
    NativeWhisperAdapter,
    NativeWindowRun,
)

__all__ = [
    "BOUNDED_PREFIX_PROFILE",
    "LEGACY_WHISPER_ENVELOPE_VERSION",
    "LegacyAdapterError",
    "LegacyExecutionMeasurements",
    "LegacyExecutionProfile",
    "LegacyInputProvenance",
    "LegacyOptionsMutationError",
    "LegacyPayloadError",
    "LegacyTranscriptionEnvelope",
    "LegacyTranscriptionRetainedError",
    "LegacyTranscribeOptions",
    "LegacyWhisperAdapter",
    "LegacyWhisperModel",
    "ModelIdentityProbe",
    "NativeAdapterError",
    "AudioBufferFullError",
    "AudioSequenceError",
    "NativeDecodeContractError",
    "NativeDecodeOptions",
    "NativeDecodeRun",
    "NativeDependencyError",
    "NativeExecutionProfile",
    "NativeModelIdentityProbe",
    "NativeStreamConfig",
    "NativeStreamError",
    "NativeTranscriptStream",
    "NativeWindowRun",
    "NativeWhisperAdapter",
    "StreamEventKind",
    "StreamMetrics",
    "TranscriptEvent",
]
